
version: '3'

services:
  ingest1:
    build:
      context: ./ingest/
      dockerfile: ./ingest/ingest.Dockerfile
    command: q /home/ingest/ingest/ingest.q
    volumes:
      - ./:/home/ingest
    working_dir: /home/ingest
    networks:
      - env-net 
    ports:
      - "4999:4999"

  ingest2:
    build:
      context: ./ingest/
      dockerfile: ./ingest/ingest.Dockerfile
    command: q /home/ingest/ingest/ingest.q
    volumes:
      - ./:/home/ingest
    working_dir: /home/ingest
    networks:
      - env-net 
    ports:
      - "4999:4999"

  gateway:
    build:
      context: ./ingest/
      dockerfile: ./ingest/ingest.Dockerfile
    command: q /home/ingest/ingest/ingest.q
    volumes:
      - ./:/home/ingest
    working_dir: /home/ingest
    networks:
      - env-net 
    ports:
      - "4999:4999"

  env1:
    build:
      context: ./qenv/
      dockerfile: ./qenv/Dockerfile
    command: q /home/qenv/server.q
    volumes:
      - ./:/home/qenv
    working_dir: /home/qenv
    depends_on:
      - gateway
    networks:
      - env-net 
    ports:
      - "5001:5000"

  # environment (exchange) 1 (first actor/actor group)
  env2:
    build:
      context: ./qenv/
      dockerfile: ./qenv/Dockerfile
    command: q /home/qenv/server.q
    volumes:
      - ./:/home/qenv
    working_dir: /home/qenv
    depends_on:
      - gateway
    networks:
      - env-net 
    ports:
      - "5002:5000"

  # environment (exchange) 3 (third actor/actor group)
  env3:
    build:
      context: ./qenv/
      dockerfile: ./qenv/Dockerfile
    command: q /home/qenv/server.q
    volumes:
      - ./:/home/qenv
    working_dir: /home/qenv
    depends_on:
      - gateway
    networks:
      - env-net 
    ports:
      - "5003:5000"



networks:
   env-net:
      driver: bridge
