
version: '3'

services:
  ingest:
    image: gcr.io/practice-275123/kdbml:v1.6
    command: q /home/ingest/ingest/ingest.q
    volumes:
      - ./:/home/ingest
    working_dir: /home/ingest
    networks:
      - env-net 
    ports:
      - "4999:4999"

  env1:
    image: gcr.io/practice-275123/kdbml:v1.6
    command: q /home/qenv/server.q
    volumes:
      - ./:/home/qenv
    working_dir: /home/qenv
    depends_on:
      - ingest
    networks:
      - env-net 
    ports:
      - "5001:5000"

  # environment (exchange) 1 (first actor/actor group)
  env2:
    image: gcr.io/practice-275123/kdbml:v1.6
    command: q /home/qenv/server.q
    volumes:
      - ./:/home/qenv
    working_dir: /home/qenv
    depends_on:
      - ingest
    networks:
      - env-net 
    ports:
      - "5002:5000"

  # environment (exchange) 3 (third actor/actor group)
  env3:
    image: gcr.io/practice-275123/kdbml:v1.6
    command: q /home/qenv/server.q
    volumes:
      - ./:/home/qenv
    working_dir: /home/qenv
    depends_on:
      - ingest
    networks:
      - env-net 
    ports:
      - "5003:5000"



networks:
   env-net:
      driver: bridge
